### Paper

POST http://localhost:5153/api/Paper
Content-Type: application/json

{
  "name": "Gold paper",
  "discontinued": true,
  "stock": 100,
  "price": 999.80
}

###

GET http://localhost:5153/api/Paper
Accept: application/json

###

# Remember to change the id to a valid number!
GET http://localhost:5153/api/Paper/{{id}}
Accept: application/json


###

# Remember to change the id to a valid number!
PUT http://localhost:5153/api/Paper/update/1
Content-Type: application/json

{
  "id": 1,
  "discontinued": false,
  "stock": 200
}

###
# Remember to change the id to a valid number!
POST http://localhost:5153/api/Paper/{{id}}/features
Content-Type: application/json

{
  "paperId": 0,
  "featureIds": [
    0
  ]
}

###