-- Drop the existing schema if needed
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

-- Table for customers
CREATE TABLE customers (
                           id integer GENERATED BY DEFAULT AS IDENTITY,
                           name character varying(255) NOT NULL,
                           address character varying(255),
                           phone character varying(50),
                           email character varying(255),
                           CONSTRAINT customers_pkey PRIMARY KEY (id)
);

-- Table for papers
CREATE TABLE paper (
                       id integer GENERATED BY DEFAULT AS IDENTITY,
                       name character varying(255) NOT NULL,
                       discontinued boolean NOT NULL DEFAULT FALSE,
                       stock integer NOT NULL DEFAULT 0,
                       price double precision NOT NULL,
                       CONSTRAINT paper_pkey PRIMARY KEY (id)
);

-- Table for features
CREATE TABLE feature (
                         id integer GENERATED BY DEFAULT AS IDENTITY,
                         feature_name character varying(255) NOT NULL,
                         CONSTRAINT features_pkey PRIMARY KEY (id)
);

-- Table for orders
CREATE TABLE orders (
                        id integer GENERATED BY DEFAULT AS IDENTITY,
                        order_date timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
                        delivery_date date,
                        status integer NOT NULL DEFAULT 0 CHECK (status IN (0, 1, 2)),  -- 0: Pending, 1: Shipped, 2: Delivered
                        total_amount double precision NOT NULL,
                        customer_id integer,
                        CONSTRAINT orders_pkey PRIMARY KEY (id),
                        CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE
);

-- Table for paper features (relation between papers and features)
CREATE TABLE paper_features (
                                feature_stock integer,
                                paper_id integer NOT NULL,
                                feature_id integer NOT NULL,
                                CONSTRAINT paper_features_pkey PRIMARY KEY (paper_id, feature_id),
                                CONSTRAINT paper_features_paper_id_fkey FOREIGN KEY (paper_id) REFERENCES paper (id),
                                CONSTRAINT paper_features_feature_id_fkey FOREIGN KEY (feature_id) REFERENCES feature (id)
);

-- Table for order entries (products associated with orders)
CREATE TABLE order_entries (
                               id integer GENERATED BY DEFAULT AS IDENTITY,
                               quantity integer NOT NULL,
                               product_id integer,
                               order_id integer,
                               CONSTRAINT order_entries_pkey PRIMARY KEY (id),
                               CONSTRAINT order_entries_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders (id),
                               CONSTRAINT order_entries_product_id_fkey FOREIGN KEY (product_id) REFERENCES paper (id)
);

-- Unique index for customer emails
CREATE UNIQUE INDEX customers_email_key ON customers (email);

-- Indexes for performance
CREATE INDEX "IX_order_entries_order_id" ON order_entries (order_id);
CREATE INDEX "IX_order_entries_product_id" ON order_entries (product_id);
CREATE INDEX "IX_orders_customer_id" ON orders (customer_id);
CREATE UNIQUE INDEX unique_product_name ON paper (name);
CREATE INDEX "IX_paper_features_feature_id" ON paper_features (feature_id);
