services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: dunderuser
      POSTGRES_PASSWORD: dunderpass
      POSTGRES_DB: dunderdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
