### Order

POST http://localhost:5153/api/Order
Content-Type: application/json

{
  "orderDate": "2024-09-26T08:20:37.569Z",
  "deliveryDate": "2024-09-26",
  "status": "string",
  "totalAmount": 1,
  "customerId": 1,
  "orderEntries": [
    {
      "quantity": 1,
      "productId": 3
    }
  ]
}
