### Order

POST http://localhost:5153/api/Order
Content-Type: application/json

{
  "orderDate": "2024-09-26T08:20:37.569Z",
  "deliveryDate": "2024-09-26",
  "status": "Pending",
  "totalAmount": 1,
  "customerEmail": "john.doe@example.com",
  "orderEntries": [
    {
      "quantity": 1,
      "productId": 3
    }
  ]
}


### 

GET http://localhost:5153/api/Order
Content-Type: application/json


###

# Remember to change the id to a valid number!
GET http://localhost:5153/api/order/2
Content-Type: application/json

###

PUT http://localhost:5153/api/order/update/2
Content-Type: application/json

{
  "id": 2,
  "deliveryDate": "2024-09-29",
  "status": "Shipped", 
  "totalAmount": 2
}



###

//Patches order nr. 2.
PATCH http://localhost:5153/api/Order/2/DecreaseStock
Content-Type: application/json

{
  "productId": 3,
  "quantity": 10
}

